Update manage-branch-version-file.yml

diff --git a/.github/workflows/manage-branch-version-file.yml b/.github/workflows/manage-branch-version-file.yml
--- a/.github/workflows/manage-branch-version-file.yml
+++ b/.github/workflows/manage-branch-version-file.yml
@@ -124,9 +124,9 @@ jobs:
                    -X PUT --data '{ "fields": { "customfield_10029" : "'"$GITHUB_WORKFLOW_ID"'" }}' \
                    -H "Content-Type: application/json" https://naregkar.atlassian.net/rest/api/3/issue/${{ env.JiraId }}
 
-               if [[ "${{ env.JiraIssue_Status }}" = "\"Ready to Merge\"" ]]; then
-                 echo "PR can be merged to master"
-               else
-                 echo "Jira Issue's status is not Ready to Merge. Cannot Merge to master."
-                 exit 1
-               fi
+               #if [[ "${{ env.JiraIssue_Status }}" = "\"Ready to Merge\"" ]]; then
+               #  echo "PR can be merged to master"
+               #else
+               #  echo "Jira Issue's status is not Ready to Merge. Cannot Merge to master."
+               #  exit 1
+               #fi
